name: push

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    name: "Build and push ${{ github.ref_name }}"

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:./"
          push: true
          build-args: VERSION=${{ github.ref_name }}
          tags: ghcr.io/alexislefebvre/deployer:${{ github.ref_name }}
